SELECT [ride_id]
      ,[started_at]
      ,[ended_at]
      ,[start_station_name]
      ,[start_station_id]
      ,[end_station_name]
      ,[end_station_id]
      ,[member_casual]
      ,[start_date]
      ,[end_date]
      ,[start_time]
      ,[end_time]
      ,[ride_length]
      ,[day_of_week]
  FROM [Cyclistic BikeShare].[dbo].[bikeride]
